apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
 name: knative-serving
 namespace: knative-serving
 annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  config:
    tracing:
      backend: zipkin
      zipkin-endpoint: http://jaeger-collector.knative-serving.svc:9411/api/v2/spans
      sample-rate: "0.1"
