apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: preview
  name: elasticsearch-operator
  source: devint-operators
  sourceNamespace: openshift-operators
