apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastichsearch
  namespace: openshift-operators
spec:
  channel: preview
  name: elasticsearch-operator
  source: devint-operators
  sourceNamespace: openshift-operators
