apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger
  namespace: openshift-operators
spec:
  channel: stable
  name: jaeger-product
  source: devint-operators
  sourceNamespace: openshift-operators
