apiVersion: v1
kind: Namespace
metadata:
  name: keda
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: keda.k8s.io/v1alpha1
kind: KedaController
metadata:
  name: keda
  namespace: keda
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  watchNamespace: ''
  logLevel: info
  logLevelMetrics: '0'
