apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: knative-kafka-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  channel: alpha
  name: knative-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
