---
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: rhpipeline-operators
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: rhpipeline
  displayName: "rhpipeline Operators"
  publisher: "rhpipeline"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhpipeline-pipelines-subscription
  namespace: openshift-operators
spec:
  channel: experimental
  name: openshift-pipelines-operator
  source: rhpipeline-operators
  sourceNamespace: openshift-marketplace
