---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ci-openshift-pipelines-storage
  namespace: ci-openshift-pipelines
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-openshift-pipelines-collectlog-database
  namespace: ci-openshift-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ci-openshift-pipelines-storage
  resources:
    requests:
      storage: 1G
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-openshift-pipelines-static
  namespace: ci-openshift-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ci-openshift-pipelines-storage
  resources:
    requests:
      storage: 1G
