apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: "1.0"
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-operators
