apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.2.5

patchesStrategicMerge:
- argocd-cm.yaml

namespace: argocd
